[pytest]
filterwarnings =
    ignore:Please use `import python_multipart` instead\.:PendingDeprecationWarning:starlette\.formparsers
    ignore:Field "model_.*" has conflict with protected namespace "model_"\.:UserWarning:pydantic\._internal\._fields
